export enum Roles {
  CARLY_ADMINISTRATOR = 'CARLY_ADMINISTRATOR',
  CARLY_COMPANY = 'CARLY_COMPANY',
  CARLY_CUSTOMER = 'CARLY_CUSTOMER',
  CARLY_FACTORY = 'CARLY_FACTORY',
  CARLY_DEFAULT = 'CARLY_DEFAULT'
}
